[tool.poetry]
name = "hw08"
version = "0.1.0"
description = ""
authors = ["Alexey Vedmedev <al.vedmedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Faker = "^15.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
